[0.363s] Invoking command in '/home/umarv/ws/build/nav2_straightline_planner': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/umarv/ws/src/install/nav2_gps_waypoint_follower_demo:/home/umarv/ws/install/nav2_gps_waypoint_follower_demo:/opt/ros/humble /usr/bin/cmake --build /home/umarv/ws/build/nav2_straightline_planner -- -j8 -l8
[0.645s] [100%] Built target nav2_straightline_planner_plugin
[0.654s] Invoked command in '/home/umarv/ws/build/nav2_straightline_planner' returned '0': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/umarv/ws/src/install/nav2_gps_waypoint_follower_demo:/home/umarv/ws/install/nav2_gps_waypoint_follower_demo:/opt/ros/humble /usr/bin/cmake --build /home/umarv/ws/build/nav2_straightline_planner -- -j8 -l8
[0.681s] Invoking command in '/home/umarv/ws/build/nav2_straightline_planner': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/umarv/ws/src/install/nav2_gps_waypoint_follower_demo:/home/umarv/ws/install/nav2_gps_waypoint_follower_demo:/opt/ros/humble /usr/bin/cmake --install /home/umarv/ws/build/nav2_straightline_planner
[0.687s] [31mCMake Error at cmake_install.cmake:46 (file):
[0.687s]   file INSTALL cannot set permissions on
[0.687s]   "/home/umarv/ws/install/nav2_straightline_planner/share/nav2_straightline_planner/global_planner_plugin.xml":
[0.687s]   Operation not permitted.
[0.687s] 
[0.688s] [0m
[0.688s] -- Install configuration: ""
[0.688s] -- Up-to-date: /home/umarv/ws/install/nav2_straightline_planner/share/nav2_straightline_planner/global_planner_plugin.xml
[0.738s] Invoked command in '/home/umarv/ws/build/nav2_straightline_planner' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/umarv/ws/src/install/nav2_gps_waypoint_follower_demo:/home/umarv/ws/install/nav2_gps_waypoint_follower_demo:/opt/ros/humble /usr/bin/cmake --install /home/umarv/ws/build/nav2_straightline_planner
[0.880s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 84, in build
    create_environment_scripts(
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 89, in create_environment_scripts
    create_file_with_runtime_dependencies(prefix_path, pkg))
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 172, in create_file_with_runtime_dependencies
    path.write_text(
  File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/home/umarv/ws/install/nav2_straightline_planner/share/colcon-core/packages/nav2_straightline_planner'
